name: Main
on:
  push:
    branches: [main]
  pull_request:
    branches:
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: work 1 - pobranie kodu
    users: actions/checkout@v3
    - name: Krok 2 - podpięcie Node.js
    uses: actions/setup-nodev2
    with:
      node-version: "18.x"

    - name: Instalacja dependencji
    run: npm install 
    - name: Uruchomienie testów
    run: npm test
